### ISSUE TITLE
Getting a lot of failed downloads

### ISSUE THREAD

**Issue by RandomLegend** [justin025/onthespot#3]
Putting in a playlist of mine i get a lot of failed downloads, i'd say roughly 50% of the playlist is failing, the songs do definetely exist on spotify and are playable.

This is the terminal output for on of them, they all look like this:

```
[2024-09-02 23:27:53,707 :: spotutils :: /home/RandomLegend/Downloads/onthespot/onthespot/src/onthespot/utils/spotify.py -> 103:       sanitize_data() :: INFO] -> Sanitising string: "Stellar"; Allow path separators: False
[2024-09-02 23:27:53,707 :: spotutils :: /home/RandomLegend/Downloads/onthespot/onthespot/src/onthespot/utils/spotify.py -> 103:       sanitize_data() :: INFO] -> Sanitising string: "Masquerade"; Allow path separators: False
[2024-09-02 23:27:53,707 :: spotutils :: /home/RandomLegend/Downloads/onthespot/onthespot/src/onthespot/utils/spotify.py -> 103:       sanitize_data() :: INFO] -> Sanitising string: "Masquerade"; Allow path separators: False
[2024-09-02 23:27:53,707 :: spotutils :: /home/RandomLegend/Downloads/onthespot/onthespot/src/onthespot/utils/spotify.py -> 103:       sanitize_data() :: INFO] -> Sanitising string: "Stellar"; Allow path separators: False
[2024-09-02 23:27:53,707 :: spotutils :: /home/RandomLegend/Downloads/onthespot/onthespot/src/onthespot/utils/spotify.py -> 103:       sanitize_data() :: INFO] -> Sanitising string: "2022 Stellar"; Allow path separators: False
Audio key error, code: 2
Audio key error, code: 2
[2024-09-02 23:27:54,235 :: worker.downloader.SESSION_DL_TH-768b3b82-2ebe-43d8-88a8-370351388c98 :: /home/RandomLegend/Downloads/onthespot/onthespot/src/onthespot/worker/downloader.py -> 221:      download_track() :: ERROR] -> Download failed for track by id '6UnOxNp0jZfFXyKcAtJwUj', Unexpected error: Traceback (most recent call last):
  File "/home/RandomLegend/Downloads/onthespot/onthespot/src/onthespot/worker/downloader.py", line 122, in download_track
    stream = session.content_feeder().load(track_id, VorbisOnlyAudioQuality(quality), False, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/RandomLegend/Downloads/onthespot/onthespot/venv/lib/python3.12/site-packages/librespot/audio/__init__.py", line 739, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/RandomLegend/Downloads/onthespot/onthespot/venv/lib/python3.12/site-packages/librespot/audio/__init__.py", line 800, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/RandomLegend/Downloads/onthespot/onthespot/venv/lib/python3.12/site-packages/librespot/audio/__init__.py", line 754, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/RandomLegend/Downloads/onthespot/onthespot/venv/lib/python3.12/site-packages/librespot/audio/__init__.py", line 339, in load_track
    key = session.audio_key().get_audio_key(track.gid, file.file_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/RandomLegend/Downloads/onthespot/onthespot/venv/lib/python3.12/site-packages/librespot/audio/__init__.py", line 277, in get_audio_key
    return self.get_audio_key(gid, file_id, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/RandomLegend/Downloads/onthespot/onthespot/venv/lib/python3.12/site-packages/librespot/audio/__init__.py", line 278, in get_audio_key
    raise RuntimeError(
RuntimeError: Failed fetching audio key! gid: (dontknowifthisissecret), fileId: (dontknowifthisissecret)
 !
[2024-09-02 23:27:54,235 :: worker.downloader.SESSION_DL_TH-768b3b82-2ebe-43d8-88a8-370351388c98 :: /home/RandomLegend/Downloads/onthespot/onthespot/src/onthespot/worker/downloader.py -> 384:                 run() :: ERROR] -> Download process returned false: 6UnOxNp0jZfFXyKcAtJwUj
```

i'm on arch linux, newest kernel, using the portable python version and installed the requirements inside a python venv.

**Comment by RandomLegend** [comment]
Alright, either it was completely restarting my PC (didn't think that could solve any issues with that :D) or it was the fact that i readded the playlist completely - either and / or both of those steps fixed the issue.

**Comment by RandomLegend** [comment]
Ha nope, just started doing it again!

After processing 66 songs, it started to fail again

**Comment by RandomLegend** [comment]
So after searching for that specific error i stumbled accross multiple github entries from various librespot implementations ([1](https://github.com/kokarare1212/librespot-python/issues/276), [2](https://github.com/librespot-org/librespot-java/discussions/926), [3](https://github.com/librespot-org/librespot-java/issues/268)) and none of them seemed fixed 🤔 

Letting it process the list until it's done, quitting the application and restarting the playlist seems to get me through it pass by pass. So i'd guess it'll take me around 7-10 restarts of the application to get my whole list downloaded.

I take what i can get, but maybe this is fixable?

**Comment by justin025** [comment]
Sometimes when it fails on a specific song, in your case 67, it means there is something wrong with that song. From the people I've spoke to it could be a podcast duplicate or special characters in the title/metadata. You can try removing that song from your playlist, bulk downloading and then downloading that song separately.

I hear the original dev is working on a fix for the playlist api but it will take some time to be pushed upstream.

**Comment by RandomLegend** [comment]
Alright, thanks for that.

Would it be possible for you to make a button that would allow users to copy the links of all failed songs?
So in my example i would paste my playlist link, let it go through, start to fail at some point and then there would be a button and with that button i'd have a list of all failed songs that i could paste again so it doesn't have to go through the playlist again?

**Comment by maguirreg** [comment]
The issue occurs with both playlists and podcasts. I traced it down to the call that retrieves information about the media item [here](https://github.com/justin025/onthespot/blob/84b26733f5eacf82770789bf4e08a288b821d4b1/src/onthespot/worker/downloader.py#L240). The problem isn't due to an error with the media itself; instead, I suspect it might be related to the interface with the source. It's possible they’ve implemented a request limit within a certain time frame. Even after increasing the download delay to 10, the error persists. Running with download delay of 15 gave me better results for a moment allowing me to download more items, but started to fail again after a couple more.
I believe one solution would be to save all failed ones to retry them after, or implement something like a database with the MediaID and details to avoid making too many requests for the same unchanged data.

**Comment by RandomLegend** [comment]
Yeah after looking into my failed downloads i saw that there are some tracks in there that don't have any special character or anything.

Examaple - Runaway from The Corrs

Decreasing the amount of workers to "1" and increasing the wait time to "15" made it much more stable for me. I was able to download a whole playlist without a single fail now.

**Comment by justin025** [comment]
The function you linked above seems to be for downloading episodes which are a little different, download_track is at lines 33-222 in the same file. It could definitely be a rate limit error but we would probably see a '400' http request somewhere in the log, see 204 for example. I do know a 'request cache' already exists but the problem is not metadata and songs in a playlist but the ogg file itself. If you guys are right its more likely that spotify has placed limits on the most bandwidth intensive media, that being streams.

I'll need to look into errors like these at some point. Thank you for sharing.

**Comment by justin025** [comment]
I know some people are sensitive about sharing their playlists but would you mind sharing links to any playlists that break so I can compile a list to test. If you don't feel comfortable sharing publicly you can dm me on discord j075046

**Comment by maguirreg** [comment]
This is my last attempt:
1. Download delay = 5, Max download Workers = 3
2. Tried to download [Case 63](https://open.spotify.com/show/4c9ZKaFtEKweSYOlYvxfvp), for the first time after 5 hours without using the app.
3. First run, it downloaded all 22 tracks. Cleared the completed/cancelled items and tried again
4. Second run, failed on the 3rd, 7th, 14th, 15th, 17th-22nd tracks, same "Failed fetching audio key" error
It suppose to skip the already downloaded items, but when is trying to get the info from the media it fails.
![image](https://github.com/user-attachments/assets/bba9ceed-a833-4301-a07b-52112a78e6bf)
![image](https://github.com/user-attachments/assets/2fb95f51-c2d8-40e2-a8ac-28fafa276688)
[output.log](https://github.com/user-attachments/files/16848974/output.log)
I'm attaching the logs for another execution where several others failed for the same list

**Comment by justin025** [comment]
Definitely a rate limit issue. I downloaded the podcast and the first time it worked flawlessly. The second time it downloaded like so: 
![2024-09-03_10-37](https://github.com/user-attachments/assets/5cfbb055-ac3e-4e56-95af-1190f11fd43e)
I'm afraid I have no solution to this at the moment so I will reopen the issue until I can either add logging informing the user they are being rate limited or figure out a solution.

For any users experiencing this, just try closing and opening the app or waiting a little while and try again.

**Comment by spyblog91** [comment]
FYI I had the same issue, however for me failing beings to appear if the PC goes in to sleep/display off while downloading and once i logged in songs starts to fail. 

_**Reason must be internet goes to sleep/refresh to save power, and that interrupts the download Metadata link from spotify (if you use as i heard and understood**_

**My FIX_** keep turn on the display and keep the device awake (remove sleepings) while downloading , i was able to download a custom playlist with 300+ songs without failing any song.

Hope this fix will help someone! Cheers and happy onthespotting!

**Comment by zerog13** [comment]
Changing the Download Delay to 25 has fixed my download rates 100%, even the metadata errors.

**Comment by zerog13** [comment]
> This is my last attempt:
> 
>     1. Download delay = 5, Max download Workers = 3
> 
>     2. Tried to download [Case 63](https://open.spotify.com/show/4c9ZKaFtEKweSYOlYvxfvp), for the first time after 5 hours without using the app.
> 
>     3. First run, it downloaded all 22 tracks. Cleared the completed/cancelled items and tried again
> 
>     4. Second run, failed on the 3rd, 7th, 14th, 15th, 17th-22nd tracks, same "Failed fetching audio key" error
>        It suppose to skip the already downloaded items, but when is trying to get the info from the media it fails.
>        ![image](https://private-user-images.githubusercontent.com/734215/363984409-bba9ceed-a833-4301-a07b-52112a78e6bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzM3NDUsIm5iZiI6MTcyNjIzMzQ0NSwicGF0aCI6Ii83MzQyMTUvMzYzOTg0NDA5LWJiYTljZWVkLWE4MzMtNDMwMS1hMDdiLTUyMTEyYTc4ZTZiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxMzE3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTQ0YWMwZTg2OWFlMzU3MmQxMDk4ZjhlMDU4ZWQ1ZTBlYjhlMTRjYmFkMzllYzllZWIwMjUyZDhmNTIyZGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DYz5mNU49eb6ZH1N691Or8MkregCHu9M9NnOjrAddDo)
>        ![image](https://private-user-images.githubusercontent.com/734215/363988210-2fb95f51-c2d8-40e2-a8ac-28fafa276688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzM3NDUsIm5iZiI6MTcyNjIzMzQ0NSwicGF0aCI6Ii83MzQyMTUvMzYzOTg4MjEwLTJmYjk1ZjUxLWMyZDgtNDBlMi1hOGFjLTI4ZmFmYTI3NjY4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxMzE3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjNmYTEwMzNlZjgxMGIyZjFkMTZkZTVmZWY4NGUyMzQ5MmFkOTcxOGJmYmRlYmRlMGEzYjg0NjFiNThmODdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DmOLKiDPIm7eVHGVoSMU_X4g7aO7S30PZsB-skWmuQE)
>        [output.log](https://github.com/user-attachments/files/16848974/output.log)
>        I'm attaching the logs for another execution where several others failed for the same list

Change download rate to 25, it fixed my issue 100%. no errors on the last 350 tracks downloaded.

**Comment by zerog13** [comment]
> This is my last attempt:
> 
>     1. Download delay = 5, Max download Workers = 3
> 
>     2. Tried to download [Case 63](https://open.spotify.com/show/4c9ZKaFtEKweSYOlYvxfvp), for the first time after 5 hours without using the app.
> 
>     3. First run, it downloaded all 22 tracks. Cleared the completed/cancelled items and tried again
> 
>     4. Second run, failed on the 3rd, 7th, 14th, 15th, 17th-22nd tracks, same "Failed fetching audio key" error
>        It suppose to skip the already downloaded items, but when is trying to get the info from the media it fails.
>        ![image](https://private-user-images.githubusercontent.com/734215/363984409-bba9ceed-a833-4301-a07b-52112a78e6bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDE5NTEsIm5iZiI6MTcyNjMwMTY1MSwicGF0aCI6Ii83MzQyMTUvMzYzOTg0NDA5LWJiYTljZWVkLWE4MzMtNDMwMS1hMDdiLTUyMTEyYTc4ZTZiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQwODE0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTkyYTczZThmNTBhYjljMzJjNjNlNzlkODE0ZjBlNmVkZDAzOThjN2RhN2VkZTA2NWU0NjY3YzliNTg2NTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wqNRGXCHCztU35kWLOerkUNi0-jf5iHlWFR7v45UHEI)
>        ![image](https://private-user-images.githubusercontent.com/734215/363988210-2fb95f51-c2d8-40e2-a8ac-28fafa276688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDE5NTEsIm5iZiI6MTcyNjMwMTY1MSwicGF0aCI6Ii83MzQyMTUvMzYzOTg4MjEwLTJmYjk1ZjUxLWMyZDgtNDBlMi1hOGFjLTI4ZmFmYTI3NjY4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQwODE0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWU2YmE4ODFhMDIyZDliOGQ3NmU1ODcwMTA2NDI3YzE4N2E2NDNlMGRlOGRkYzAxMjRiZWIxNTFiYTM2OTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SmTogjukA8sy4iPxkHn6bJiD0KVK5T-IOZMcoWZ7DpE)
>        [output.log](https://github.com/user-attachments/files/16848974/output.log)
>        I'm attaching the logs for another execution where several others failed for the same list

try this plugin for podcasts - Podcasts - A player, downloader, transcriber https://podcasts.bluepill.life/index.html

**Comment by justin025** [comment]
Although this doesn't necessarily fix the issue, in the latest release I've added the feature to rotate the currently downloading account in an effort to reduce rate limits

**Comment by bulasag** [comment]
I'm getting failed on all songs. Tried closing, waiting 15mins, opening and trying again but same thing happens. How do I see terminal output on the exe in W11?

**Comment by justin025** [comment]
You can copy the exe into git bash and can see the output there or its available at %localappdata%/Temp/onthespot/logs

**Comment by PZaphiro** [comment]
Not sure if this is still an issue for others, but I was experiencing all failures today until I applied these settings below. Now, I don't experience a single failed download. What I do experience every now and again is every song status sitting at "Waiting" after 100-200 songs download, and then nothing happens after that unless I restart the app. Still better than failures I guess!

Download Delay: 15s
Download Chunk Size (b): 25000 (this made the biggest difference for me)
Maximum Queue Workers: 2
Maximum Download Workers: 1
Enable Retry Worker: Enabled
Retry Delay (m): 10

**Comment by gitty6938** [comment]
changing above settings did nothing.  Running onthespot with admin fixed the issue below.  Not sure why.

[2025-04-27 10:51:05,424 :: downloader :: downloader.py -> 653:                 run() :: INFO] -> Download failed: {'local_id': '4A5CxrDn5iFFSK8Pt6cVCk-0', 'available': False, 'item_service': 'spotify', 'item_type': 'track', 'item_id': '4A5CxrDn5iFFSK8Pt6cVCk', 'item_status': 'Downloading', 'file_path': None, 'parent_category': 'playlist', 'playlist_name': 'Current', 'playlist_by': 'jarodp18', 'playlist_number': '110', 'gui': {'item_label': <PyQt6.QtWidgets.QLabel object at 0x0000025E9C492AD0>, 'status_label': <PyQt6.QtWidgets.QLabel object at 0x0000025E9C4928F0>, 'progress_bar': <PyQt6.QtWidgets.QProgressBar object at 0x0000025E9C4925D0>, 'btn': {'actions': <onthespot.gui.dl_progressbtn.DownloadActionsButtons object at 0x0000025E9C492990>, 'copy': None, 'cancel': <PyQt6.QtWidgets.QPushButton object at 0x0000025E9C4922B0>, 'retry': <PyQt6.QtWidgets.QPushButton object at 0x0000025E9C492670>, 'open': <PyQt6.QtWidgets.QPushButton object at 0x0000025E9C492710>, 'locate': <PyQt6.QtWidgets.QPushButton object at 0x0000025E9C4927B0>, 'delete': None}}}, Error: Failed fetching audio key! gid: 968dbbde61ea4118bdaf6d0197506c4c, fileId: b4acb7c036f8fd5e1343420dd60b9ca3725852b0
Traceback: Traceback (most recent call last):
  File "downloader.py", line 270, in run
  File "librespot\audio\__init__.py", line 739, in load
  File "librespot\audio\__init__.py", line 800, in load_track
  File "librespot\audio\__init__.py", line 754, in load_stream
  File "librespot\audio\__init__.py", line 339, in load_track
  File "librespot\audio\__init__.py", line 277, in get_audio_key
  File "librespot\audio\__init__.py", line 278, in get_audio_key
RuntimeError: Failed fetching audio key! gid: 968dbbde61ea4118bdaf6d0197506c4c, fileId: b4acb7c036f8fd5e1343420dd60b9ca3725852b0

**Comment by gitty6938** [comment]
clicking retry doesnt work, but closing an re-openning app works to download a few more songs

seems better if i change chuck size to 10000

**Comment by justin025** [comment]
This error is very clearly a rate limit, your download delay needs to be set to 35 for spotify
