### ISSUE TITLE
Playlist doesn't download program appears to do nothing.

### ISSUE THREAD

**Issue by ojt1998** [justin025/onthespot#35]
Hi there,

When trying to download the playlist the latest version appears to just sit and do nothing.

The log file shows:
[2024-10-23 09:41:51,181 :: spotify.api :: search.py -> 16:  get_search_results() :: INFO] -> Search clicked with value with url ************
[2024-10-23 09:41:51,183 :: runtimedata :: runtimedata.py -> 43:    handle_exception() :: CRITICAL] -> Uncaught exception
Traceback (most recent call last):
  File "gui\mainui.py", line 571, in fill_search_table
  File "search.py", line 17, in get_search_results
  File "parse_item.py", line 19, in parse_url
IndexError: list index out of range

The same playlist downloads on 0.7.0

**Comment by justin025** [comment]
The app is complaining that you do not have an account selected, maybe I should make that more clear in the logs. Please let me know if this works for you 
![2024-10-23_08-51](https://github.com/user-attachments/assets/b0d2edd3-62ad-4f1c-ab31-23de4ffb37c9)

**Comment by ojt1998** [comment]
Yes that's resolved it for me - I feel slightly silly as I hadn't had to do that before. No bother though!

Would it be worth making the radio button more visible on dark mode to make it more obvious?

**Comment by justin025** [comment]
I will make the radio button blue and add a popup error instructing the user to select an account, I hope this works
