### ISSUE TITLE
Upgrade from 0.7.1 to 1.0.2 and can't find Mirror Playback option

### ISSUE THREAD

**Issue by KiLLeRRaT** [justin025/onthespot#55]
Hi,

I can't seem to find the Mirror playback option anymore, was this removed? Or is there another way to enable this now?

Thanks,

**Comment by justin025** [comment]
It was removed, added back mirror playback in the commit below (exe at the bottom of the page). It's completely functional but I'll probably push this with the next release in a couple weeks.

https://github.com/justin025/onthespot/actions/runs/11770349152

**Comment by KiLLeRRaT** [comment]
Many thanks :)

**Comment by KiLLeRRaT** [comment]
Hmm, not quite working yet.  I can see the checkbox but downloads never appear.  I see the following exception, not sure if it's 100% related, but looks to be:

```
Attempting to use system ffmpeg binary !
Using ffmpeg binary at:  /tmp/.mount_OnTheSCFkFph/usr/bin/ffmpeg
[2024-11-11 16:19:23,082 :: __init__ :: /tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/__init__.py -> 15:                main() :: INFO] -> Starting application in
3
2
1
[2024-11-11 16:19:23,125 :: __init__ :: /tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/__init__.py -> 20:                main() :: INFO] -> OnTheSpot Version: v1.0.2
[2024-11-11 16:19:23,310 :: gui.main_ui :: /tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/gui/mainui.py -> 67:            __init__() :: INFO] -> Initialising main window, logging session : ce4efd10-300a-4697-a48a-eed207ec3e17
[2024-11-11 16:19:23,311 :: gui.main_ui :: /tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/gui/mainui.py -> 75:            __init__() :: INFO] -> Loading configurations..
[2024-11-11 16:19:23,313 :: runtimedata :: /tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/runtimedata.py -> 49:    handle_exception() :: CRITICAL] -> Uncaught exception
Traceback (most recent call last):
  File "/tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/gui/mainui.py", line 557, in set_login_fields
    self.btn_login_add.clicked.disconnect()
TypeError: disconnect() failed between 'clicked' and all its connections
[2024-11-11 16:19:23,336 :: runtimedata :: /tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/runtimedata.py -> 49:    handle_exception() :: CRITICAL] -> Uncaught exception
Traceback (most recent call last):
  File "/tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/gui/mainui.py", line 725, in manage_mirror_spotify_playback
    self.mirrorplayback.start()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'mirrorplayback'
/home/<REDACTED>/.cache/onthespot/sessions/ots_login_6f114bc3-7b5f-4442-840a-f7facc33b3e2.json
[2024-11-11 16:19:23,338 :: api.spotify :: /tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/api/spotify.py -> 27:               start() :: INFO] -> Starting SpotifyMirrorPlayback
Login information for '<REDACTED>' written to /home/<REDACTED>/.cache/onthespot/sessions/ots_login_6f114bc3-7b5f-4442-840a-f7facc33b3e2.json
[2024-11-11 16:19:23,353 :: gui.main_ui :: /tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/gui/mainui.py -> 113:            __init__() :: INFO] -> Set theme dark!
[2024-11-11 16:19:23,353 :: gui.main_ui :: /tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/gui/mainui.py -> 185:     set_table_props() :: INFO] -> Setting table item properties 683
[2024-11-11 16:19:23,353 :: gui.main_ui :: /tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/gui/mainui.py -> 117:            __init__() :: INFO] -> Main window init completed !
[2024-11-11 16:19:25,917 :: api.spotify :: /tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/api/spotify.py -> 172:  spotify_login_user() :: INFO] -> Login successful for user 'albe*******'
[2024-11-11 16:19:25,925 :: gui.main_ui :: /tmp/.mount_OnTheSCFkFph/opt/python3.12/lib/python3.12/site-packages/onthespot/gui/mainui.py -> 295:  fill_account_table() :: INFO] -> Accounts table was populated !
```

**Comment by justin025** [comment]
Launches and runs fine on linux and windows, I noticed the attribute error last night and it does not seem to be that important. As you can see right under the attribute error the service starts anyway. I don't mean to be that guy but did you play a song on spotify (desktop, mobile, or website)? It mirrors the playback of the currently selected account, heres an example

edit: I noticed my logs do not have the attribute error in the video below it only occurs when on at startup, I am still able to mirror songs when this happens. Either way I pushed a fix for the attribute error

https://github.com/user-attachments/assets/793f8c18-5936-43d0-95b6-fa343737a9eb

**Comment by KiLLeRRaT** [comment]
Hi Justin,

It still didn't work, but what worked as I removed my Spotify account and added it again, then the mirroring worked right away!


Thanks!

**Comment by justin025** [comment]
Weird that logging in again worked, glad the issue was fixed for you.

Figured I should let you know that I pushed a fix for a bug while playing a playlist item, maybe this was the error you were facing. This should be the final commit for this feature, enjoy
