### ISSUE TITLE
Add setting to remember search settings

### ISSUE THREAD

**Issue by legaldeejay** [justin025/onthespot#59]
### Feature Description

Add setting to remember search settings

### Justification

So that you do not have to keep unchecking options

### Additional Information

For example, if I only want to search for Tracks, I will uncheck everything else and just check that.  The program should remember that option, otherwise, you have to keep unchecking the other options everytime you start the program.

**Comment by justin025** [comment]
Added in the latest commit, you can get the exe under the actions tab in github.

**Comment by legaldeejay** [comment]
Thanks.  I had to use commit #99 for Windows because I received error messages when trying the more recent commits for Windows, including #105.

**Comment by legaldeejay** [comment]
Not sure why my message appeared the way it did so I will try again.  Thanks. I had to use release number 99 for Windows because I received error messages when trying the more recent commits for Windows, including release number 105.

**Comment by justin025** [comment]
Thats odd, I didn't change the login mechanism in any way can you please share your logs they should be located at %localappdata%/Temp/onthespot

**Comment by legaldeejay** [comment]
Here you go:

[2024-11-18 21:01:25,774 :: runtimedata :: runtimedata.py -> 49:    handle_exception() :: CRITICAL] -> Uncaught exception
Traceback (most recent call last):
  File "portable.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "__init__.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "gui\mainui.py", line 20, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "downloader.py", line 12, in <module>
ModuleNotFoundError: No module named 'onthespot.post_download'

**Comment by justin025** [comment]
fixed in 1.0.3
