### ISSUE TITLE
Windows Build 108 not working

### ISSUE THREAD

**Issue by legaldeejay** [justin025/onthespot#68]
Traceback (most recent call last):
  File "portable.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "__init__.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "gui\mainui.py", line 20, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "downloader.py", line 12, in <module>
ModuleNotFoundError: No module named 'onthespot.post_download'

**Comment by legaldeejay** [comment]
FYI, I get the same error for all Release Builders 100-108 on Windows 10.  99 is the last Release Builder that works for me.

**Comment by justin025** [comment]
It wasn't finished yet lol, 109 fixes the issue but it seems like my account has been ratelimited now, not sure how long it will take for github to process the request

there is a working exe of the latest commit available in my test repo [here](https://github.com/justin025/test/actions/runs/11976511816) I'll close this issue whenever the workflow finishes

**Comment by justin025** [comment]
should work now.
