### ISSUE TITLE
BUG: Not opening

### ISSUE THREAD

**Issue by YukiXXL** [justin025/onthespot#79]
When trying to open AppImage:
```
fusermount3 version: 3.14.0
Attempting to use system ffmpeg binary !
Using ffmpeg binary at:  /tmp/.mount_OnTheSfGolHo/usr/bin/ffmpeg
[2024-11-29 14:59:24,676 :: __init__ :: /tmp/.mount_OnTheSfGolHo/opt/python3.12/lib/python3.12/site-packages/onthespot/__init__.py -> 15:                main() :: INFO] -> Starting application in 
3
2
1
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

/tmp/.mount_OnTheSfGolHo/AppRun: line 9:  4708 Aborted                 (core dumped) "$HERE/opt/python3.12/bin/python3.12" "-m" "onthespot" "$@"
```
When trying to open binary app from Tar:
```
Traceback (most recent call last):
  File "portable.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "__init__.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "gui/mainui.py", line 9, in <module>
ModuleNotFoundError: No module named 'onthespot.utils'
[PYI-4757:ERROR] Failed to execute script 'portable' due to unhandled exception!
```
System: Linux Mint 22

**Comment by justin025** [comment]
Appimage issue seems to be fixed on latest release, tested on linux mint 22
