### ISSUE TITLE
Audiobooks not downloading - does nothing

### ISSUE THREAD

**Issue by WifiRouterYT** [justin025/onthespot#81]
I'm trying to download an Audiobook, and while it does show up in search results and everything, the download button does... well, nothing. no error, no confirmation, no nothing. pasting a link tells me its being parsed and will be added to queue soon but nothing ever happens. ill try an older version to see if that works

**Comment by WifiRouterYT** [comment]
running it from source spams this error repeatedly:

```
[2024-12-09 23:52:55,781 :: api.spotify :: G:\on the spot\onthespot\src\onthespot\api\spotify.py -> 608:spotify_get_episode_metadata() :: INFO] -> Get episode info for episode by id '6LHkspA1pSDqPwpHqPsywI'
[2024-12-09 23:52:55,782 :: gui.main_ui :: G:\on the spot\onthespot\src\onthespot\gui\mainui.py -> 56:                 run() :: ERROR] -> Unknown Exception for {'local_id': '6LHkspA1pSDqPwpHqPsywI-0', 'item_service': 'spotify', 'item_type': 'episode', 'item_id': '6LHkspA1pSDqPwpHqPsywI', 'parent_category': 'audiobook'}: sequence item 0: expected str instance, dict found
Traceback: Traceback (most recent call last):
  File "G:\on the spot\onthespot\src\onthespot\gui\mainui.py", line 48, in run
    item_metadata = globals()[f"{item['item_service']}_get_{item['item_type']}_metadata"](token, item['item_id'])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\on the spot\onthespot\src\onthespot\api\spotify.py", line 626, in spotify_get_episode_metadata
    info['copyright'] = conv_list_format(episode_data.get('show', {}).get('copyrights', ''))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\on the spot\onthespot\src\onthespot\utils.py", line 112, in conv_list_format
    return (config.get('metadata_seperator')).join(items)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, dict found
```

Changing line 626 - the one its hiccuping on - to this:
```
    try:
        info['copyright'] = conv_list_format(episode_data.get('show', {}).get('copyrights', ''))
    except:
        info['copyright'] = "n/a"
```
makes it work. Temporary workaround!

**Comment by justin025** [comment]
please provide the link

**Comment by justin025** [comment]
Should be fixed with latest commit
