### ISSUE TITLE
could not add spotify account

### ISSUE THREAD

**Issue by Gene22** [justin025/onthespot#85]
When I try to add the Spotify account (after pressing the "connect with device" button) nothing hapend.

[2024-12-20 12:16:17,107 :: gui.main_ui :: gui/mainui.py -> 132:            __init__() :: INFO] -> Main window init completed !
[2024-12-20 12:16:17,107 :: gui.main_ui :: gui/mainui.py -> 132:            __init__() :: INFO] -> Main window init completed !
[2024-12-20 12:16:17,110 :: gui.main_ui :: gui/mainui.py -> 327:  fill_account_table() :: INFO] -> Accounts table was populated !
[2024-12-20 12:16:17,110 :: gui.main_ui :: gui/mainui.py -> 327:  fill_account_table() :: INFO] -> Accounts table was populated !
[2024-12-20 12:16:25,919 :: gui.main_ui :: gui/mainui.py -> 721: add_spotify_account() :: INFO] -> Add spotify account clicked 
[2024-12-20 12:16:25,919 :: gui.main_ui :: gui/mainui.py -> 721: add_spotify_account() :: INFO] -> Add spotify account clicked 
[2024-12-20 12:16:26,731 :: api.spotify :: api/spotify.py -> 119: spotify_new_session() :: INFO] -> Zeroconf login service started

nothing hapend after this.

**Comment by justin025** [comment]
If you have discord join the community channel, I can help you better there. The logs say that the app was not detected here is a video of what you need to do please make sure you have any firewalls or vpns disabled during login.

https://github.com/user-attachments/assets/682458fb-28ae-4ba1-8557-fe458d1aa713

**Comment by Gene22** [comment]
Thanks for the video.
But I did everything exactly as described in the video - in the spotify client “OnTheSpot” is also displayed under devices, but nothing happens when you want to connect.

Here is the complete terminal output from starting the app:

./onthespot-gui
Attempting to use system ffmpeg binary !
Using ffmpeg binary at:  /usr/bin/ffmpeg
[2024-12-21 17:35:43,506 :: gui :: __init__.py -> 47:                main() :: INFO] -> Starting application in 
3
2
1
[2024-12-21 17:35:43,506 :: gui :: __init__.py -> 61:                main() :: INFO] -> OnTheSpot Version: v1.0.4
qt.gui.icc: fromIccProfile: failed size sanity 2
qt.gui.icc: fromIccProfile: failed size sanity 2
[2024-12-21 17:35:43,643 :: gui.main_ui :: gui/mainui.py -> 99:            __init__() :: INFO] -> Initialising main window, logging session : 45cd2cd9-6e0c-4076-96c7-2216aeba09ec
[2024-12-21 17:35:43,643 :: gui.main_ui :: gui/mainui.py -> 99:            __init__() :: INFO] -> Initialising main window, logging session : 45cd2cd9-6e0c-4076-96c7-2216aeba09ec
[2024-12-21 17:35:43,643 :: gui.main_ui :: gui/mainui.py -> 102:            __init__() :: INFO] -> Loading configurations..
[2024-12-21 17:35:43,643 :: gui.main_ui :: gui/mainui.py -> 102:            __init__() :: INFO] -> Loading configurations..
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
[2024-12-21 17:35:43,686 :: gui.main_ui :: gui/mainui.py -> 132:            __init__() :: INFO] -> Main window init completed !
[2024-12-21 17:35:43,686 :: gui.main_ui :: gui/mainui.py -> 132:            __init__() :: INFO] -> Main window init completed !
[2024-12-21 17:35:43,688 :: gui.main_ui :: gui/mainui.py -> 329:  fill_account_table() :: INFO] -> Accounts table was populated !
[2024-12-21 17:35:43,688 :: gui.main_ui :: gui/mainui.py -> 329:  fill_account_table() :: INFO] -> Accounts table was populated !
[2024-12-21 17:35:56,821 :: gui.main_ui :: gui/mainui.py -> 719: add_spotify_account() :: INFO] -> Add spotify account clicked 
[2024-12-21 17:35:56,821 :: gui.main_ui :: gui/mainui.py -> 719: add_spotify_account() :: INFO] -> Add spotify account clicked 
[2024-12-21 17:35:57,651 :: api.spotify :: api/spotify.py -> 119: spotify_new_session() :: INFO] -> Zeroconf login service started

closing the app
[2024-12-21 17:36:48,388 :: gui :: __init__.py -> 109:                main() :: INFO] -> Good bye ..

**Comment by justin025** [comment]
Your logs say the onthespot and spotify never communicated, which distro is this and is this the appimage or the binary?

**Comment by Gene22** [comment]
I'm using Arch Linux - i've compiled the app from Git source.

The appimage doesn't work:
/home/gene/test/onthespot/OnTheSpot-x86_64.AppImage 
execv error: No such file or directory

..and this is the downloaded Binary:
/home/gene/test/onthespot/onthespot-gui 
Attempting to use system ffmpeg binary !
Using ffmpeg binary at:  /usr/bin/ffmpeg
[2024-12-22 11:54:50,302 :: gui :: __init__.py -> 47:                main() :: INFO] -> Starting application in 
3
2
1
[2024-12-22 11:54:50,302 :: gui :: __init__.py -> 61:                main() :: INFO] -> OnTheSpot Version: v1.0.5
qt.gui.icc: fromIccProfile: failed size sanity 2
qt.gui.icc: fromIccProfile: failed size sanity 2
[2024-12-22 11:54:50,464 :: gui.main_ui :: gui/mainui.py -> 100:            __init__() :: INFO] -> Initialising main window, logging session : 27ef2315-f61e-4980-bd89-975ee936f446
[2024-12-22 11:54:50,464 :: gui.main_ui :: gui/mainui.py -> 100:            __init__() :: INFO] -> Initialising main window, logging session : 27ef2315-f61e-4980-bd89-975ee936f446
[2024-12-22 11:54:50,464 :: gui.main_ui :: gui/mainui.py -> 103:            __init__() :: INFO] -> Loading configurations..
[2024-12-22 11:54:50,464 :: gui.main_ui :: gui/mainui.py -> 103:            __init__() :: INFO] -> Loading configurations..
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
[2024-12-22 11:54:50,507 :: gui.main_ui :: gui/mainui.py -> 133:            __init__() :: INFO] -> Main window init completed !
[2024-12-22 11:54:50,507 :: gui.main_ui :: gui/mainui.py -> 133:            __init__() :: INFO] -> Main window init completed !
[2024-12-22 11:54:50,509 :: gui.main_ui :: gui/mainui.py -> 330:  fill_account_table() :: INFO] -> Accounts table was populated !
[2024-12-22 11:54:50,509 :: gui.main_ui :: gui/mainui.py -> 330:  fill_account_table() :: INFO] -> Accounts table was populated !
[2024-12-22 11:55:07,279 :: gui.main_ui :: gui/mainui.py -> 740: add_spotify_account() :: INFO] -> Add spotify account clicked 
[2024-12-22 11:55:07,279 :: gui.main_ui :: gui/mainui.py -> 740: add_spotify_account() :: INFO] -> Add spotify account clicked 
[2024-12-22 11:55:08,109 :: api.spotify :: api/spotify.py -> 119: spotify_new_session() :: INFO] -> Zeroconf login service started
[2024-12-22 11:55:15,117 :: api.spotify :: api/spotify.py -> 124: spotify_new_session() :: INFO] -> Grabbed <librespot.core.Session object at 0x741005f624a0> for sabine223
[2024-12-22 11:55:15,376 :: api.spotify :: api/spotify.py -> 155: spotify_new_session() :: INFO] -> New account added to config.
Speicherzugriffsfehler (Speicherabzug geschrieben)

..then restart:
/home/gene/test/onthespot/onthespot-gui 
Traceback (most recent call last):
  File "portable.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "gui/mainui.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "accounts.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "api/apple_music.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "otsconfig.py", line 273, in <module>
  File "otsconfig.py", line 167, in __init__
  File "json/__init__.py", line 293, in load
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[PYI-12433:ERROR] Failed to execute script 'portable' due to unhandled exception!

..and now with selfcompiled binary:

/home/gene/test/onthespot/scripts/dist/onthespot-gui 
Traceback (most recent call last):
  File "portable.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "gui/mainui.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "accounts.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "api/apple_music.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "otsconfig.py", line 273, in <module>
  File "otsconfig.py", line 167, in __init__
  File "json/__init__.py", line 293, in load
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[PYI-16105:ERROR] Failed to execute script 'portable' due to unhandled exception!


OK, now I delete the otsconfig.json (0 -rw-r--r--   1 gene users    0 22. Dez 11:55 otsconfig.json)

Starting compiled binary again:

Attempting to use system ffmpeg binary !
Using ffmpeg binary at:  /usr/bin/ffmpeg
[2024-12-22 12:03:24,636 :: gui :: __init__.py -> 47:                main() :: INFO] -> Starting application in 
3
2
1
[2024-12-22 12:03:24,637 :: gui :: __init__.py -> 61:                main() :: INFO] -> OnTheSpot Version: v1.0.5
qt.gui.icc: fromIccProfile: failed size sanity 2
qt.gui.icc: fromIccProfile: failed size sanity 2
[2024-12-22 12:03:24,783 :: gui.main_ui :: gui/mainui.py -> 100:            __init__() :: INFO] -> Initialising main window, logging session : 5b3e7244-8afb-4f4f-ae42-6aebb90e7369
[2024-12-22 12:03:24,783 :: gui.main_ui :: gui/mainui.py -> 100:            __init__() :: INFO] -> Initialising main window, logging session : 5b3e7244-8afb-4f4f-ae42-6aebb90e7369
[2024-12-22 12:03:24,784 :: gui.main_ui :: gui/mainui.py -> 103:            __init__() :: INFO] -> Loading configurations..
[2024-12-22 12:03:24,784 :: gui.main_ui :: gui/mainui.py -> 103:            __init__() :: INFO] -> Loading configurations..
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
[2024-12-22 12:03:24,826 :: gui.main_ui :: gui/mainui.py -> 133:            __init__() :: INFO] -> Main window init completed !
[2024-12-22 12:03:24,826 :: gui.main_ui :: gui/mainui.py -> 133:            __init__() :: INFO] -> Main window init completed !
[2024-12-22 12:03:26,692 :: api.soundcloud :: api/soundcloud.py -> 90:soundcloud_login_user() :: INFO] -> Refreshed SoundCloud tokens as TeyyF4yy******** 17346885********
[2024-12-22 12:03:26,904 :: gui.main_ui :: gui/mainui.py -> 330:  fill_account_table() :: INFO] -> Accounts table was populated !
[2024-12-22 12:03:26,904 :: gui.main_ui :: gui/mainui.py -> 330:  fill_account_table() :: INFO] -> Accounts table was populated !
[2024-12-22 12:03:44,807 :: gui.main_ui :: gui/mainui.py -> 740: add_spotify_account() :: INFO] -> Add spotify account clicked 
[2024-12-22 12:03:44,807 :: gui.main_ui :: gui/mainui.py -> 740: add_spotify_account() :: INFO] -> Add spotify account clicked 
[2024-12-22 12:03:45,619 :: api.spotify :: api/spotify.py -> 119: spotify_new_session() :: INFO] -> Zeroconf login service started
[2024-12-22 12:03:53,621 :: api.spotify :: api/spotify.py -> 124: spotify_new_session() :: INFO] -> Grabbed <librespot.core.Session object at 0x7fc54c0d7560> for sabine223
[2024-12-22 12:03:53,879 :: api.spotify :: api/spotify.py -> 155: spotify_new_session() :: INFO] -> New account added to config.

OK, the new self compiled version works!

it's important to delete the otsconfig.json file AND all preconfigured accounts like deezer in the app..

**Comment by justin025** [comment]
Deleting the added accounts is not necessary I just double checked by logging in again on gentoo and windows, it might be a dependency error considering the binary was able to log you in, I do know that the aur is missing pywidevine and I forked the original librespot to resolve a dependency conflict. It could also be a whole host of other things considering this is arch, perhaps the spotify binary package communicates differently, perhaps you are using conman instead of network manager, or perhaps it was something with your spotify account specifically considering the json decodes fine but with your account added it fails. I would be curious to take a look at the file, its a shame I wouldn't be able to resolve this issue without looking at your credentials. If you have a windows computer lying around, would you mind attempting a login on that, if not no worries.

thanks for reporting the issue

**Comment by Nsh-GaMeS** [comment]
@justin025 I couldn't figure out how to connect my spotify account for the longest little bit. The video above was what solved it for me. Thank you so much!
